const questionsDB = [
  // --- Tema 1: Diri Sendiri (100 Pertanyaan Intropeksi) ---
  { text: "Apa hal pertama yang kamu pikirkan saat bangun tidur?" },
  { text: "Jika hidupmu adalah sebuah film, apa judulnya untuk babak yang sedang kamu jalani sekarang?" },
  { text: "Suara apa yang paling menenangkan bagimu?" },
  { text: "Apa kebiasaan kecil yang tanpa sadar sering kamu lakukan?" },
  { text: "Jika kamu bisa makan satu makanan seumur hidup, apa yang akan kamu pilih?" },
  { text: "Apa satu hal yang bisa membuatmu merasa langsung \"hidup\"?" },
  { text: "Sifat baik apa dalam dirimu yang paling kamu syukuri?" },
  { text: "Apa definisi \"sukses\" versi kamu pribadi?" },
  { text: "Jika kamu adalah seorang pahlawan super, kekuatan apa yang akan kamu miliki dan mengapa?" },
  { text: "Apa satu hal yang akan kamu lakukan jika kamu tahu tidak akan ada yang menilaimu?" },
  { text: "Bagaimana cara kamu memaafkan diri sendiri setelah melakukan kesalahan?" },
  { text: "Apa ketakutan terbesarmu yang tidak masuk akal?" },
  { text: "Jika hidup adalah sebuah buku, bab apa yang paling ingin kamu hapus?" },
  { text: "Apa bau favoritmu dan kenapa?" },
  { text: "Apakah kamu lebih mudah percaya pada pikiran atau perasaanmu sendiri?" },
  { text: "Satu kata untuk menggambarkan dirimu saat ini?" },
  { text: "Apa hal terkecil yang bisa membuat harimu jauh lebih baik?" },
  { text: "Kapan terakhir kali kamu merasa benar-benar bangga pada dirimu sendiri?" },
  { text: "Apa yang biasanya kamu pikirkan tepat sebelum tidur?" },
  { text: "Jika kamu bisa bertukar hidup dengan satu orang selama sehari, siapa orang itu?" },
  { text: "Apakah kamu lebih suka menjadi orang yang paling pintar atau paling baik hati? Mengapa?" },
  { text: "Apa aturan pribadi yang tidak akan pernah kamu langgar?" },
  { text: "Bagaimana reaksimu saat rencana penting tiba-tiba gagal?" },
  { text: "Apakah kamu merasa mudah untuk meminta bantuan orang lain?" },
  { text: "Apa satu hal yang kamu rasa orang lain sering salah pahami tentang dirimu?" },
  { text: "Apa yang paling kamu cari dalam diri seorang teman?" },
  { text: "Jika kamu punya kekuatan untuk menghilangkan satu emosi negatif dari hidupmu, emosi apa itu?" },
  { text: "Bagaimana kamu mendefinisikan \"cinta\" dengan kata-katamu sendiri?" },
  { text: "Apa mimpi teraneh yang pernah kamu ingat?" },
  { text: "Kapan terakhir kali kamu menangis dan apa penyebabnya?" },
  { text: "Apa yang lebih penting bagimu: pengakuan dari luar atau kepuasan dari dalam?" },
  { text: "Jika kamu adalah sebuah lagu, lagu apa yang menjadi soundtrack hidupmu saat ini?" },
  { text: "Apa hal yang paling berani pernah kamu lakukan?" },
  { text: "Apa keputusan tersulit yang pernah kamu buat sendirian?" },
  { text: "Apakah kamu termasuk orang yang mudah melupakan atau mudah mengingat?" },
  { text: "Apa satu hal yang ingin kamu pelajari hanya untuk kesenangan diri sendiri?" },
  { text: "Bagaimana caramu menunjukkan kasih sayang kepada orang terdekat?" },
  { text: "Apa hal yang paling membuatmu merasa bersyukur hari ini?" },
  { text: "Apakah kamu lebih suka memberi atau menerima hadiah? Mengapa?" },
  { text: "Apa satu hal yang akan kamu ubah dari penampilan fisikmu jika bisa?" },
  { text: "Jika kamu adalah seorang seniman, karya apa yang akan kamu ciptakan?" },
  { text: "Siapa orang pertama yang akan kamu hubungi saat kamu punya kabar baik?" },
  { text: "Apakah kamu merasa sudah menjadi versi terbaik dari dirimu? Jika belum, apa yang kurang?" },
  { text: "Apa yang biasanya kamu lakukan saat merasa kesepian?" },
  { text: "Apakah kamu lebih mudah merasa iri atau kagum pada kesuksesan orang lain?" },
  { text: "Seberapa penting penampilan luar menurutmu?" },
  { text: "Apa satu hal yang bisa membuatmu langsung merasa tidak nyaman?" },
  { text: "Jika uang bukan masalah, bagaimana rutinitas harianmu akan berubah?" },
  { text: "Apakah kamu seorang planner atau spontan?" },
  { text: "Apa kualitas terbaik yang bisa kamu bawa ke dalam sebuah tim?" },
  { text: "Jika hidup adalah sebuah game, level apa yang sedang kamu hadapi saat ini?" },
  { text: "Apa satu kenangan masa kecil yang paling membentuk dirimu sekarang?" },
  { text: "Apakah kamu lebih suka berbicara atau mendengarkan dalam sebuah percakapan?" },
  { text: "Apa satu hal yang tidak akan pernah kamu kompromikan?" },
  { text: "Bagaimana cara kamu merayakan hal-hal kecil dalam hidup?" },
  { text: "Apakah kamu tipe orang yang mudah percaya atau mudah curiga?" },
  { text: "Apa yang akan kamu katakan kepada dirimu yang berusia 10 tahun?" },
  { text: "Jika kamu bisa memilih satu tempat di dunia untuk menghabiskan sisa hidupmu, di mana?" },
  { text: "Apa hal terbaik yang pernah dilakukan orang lain untukmu?" },
  { text: "Apakah kamu sering merasa bahwa waktumu tidak cukup?" },
  { text: "Apa satu hal yang kamu harap bisa lebih kamu hargai dulu?" },
  { text: "Bagaimana cara kamu mengelola stres?" },
  { text: "Apakah kamu seorang pemimpin atau pengikut yang baik? Jelaskan." },
  { text: "Apa warna favoritmu dan apa yang membuatnya spesial?" },
  { text: "Jika kamu bisa menjadi ahli dalam satu bidang dalam semalam, bidang apa itu?" },
  { text: "Apa satu pertanyaan yang paling sering kamu tanyakan pada dirimu sendiri?" },
  { text: "Apakah kamu lebih suka kesendirian atau keramaian?" },
  { text: "Mengapa?" },
  { text: "Apa yang paling kamu banggakan dari asal-usulmu atau keluargamu?" },
  { text: "Bagaimana kamu bereaksi saat dikritik?" },
  { text: "Apa satu kebiasaan buruk yang sedang kamu usahakan untuk dihilangkan?" },
  { text: "Apakah kamu merasa hidupmu saat ini memiliki tujuan yang jelas?" },
  { text: "Jika kamu adalah seekor binatang, binatang apa yang paling mewakili karaktermu?" },
  { text: "Apa yang paling kamu nanti-nantikan dalam satu minggu ke depan?" },
  { text: "Kapan terakhir kali kamu melakukan sesuatu untuk pertama kalinya?" },
  { text: "Apakah kamu merasa lebih baik di pagi hari atau malam hari?" },
  { text: "Apa yang membuatmu merasa aman?" },
  { text: "Jika bisa, satu pesan apa yang akan kamu sampaikan ke seluruh dunia?" },
  { text: "Apa hal yang paling tidak penting tapi sangat kamu nikmati?" },
  { text: "Apakah kamu termasuk orang yang cepat puas atau selalu menginginkan lebih?" },
  { text: "Bagaimana caramu menghadapi kekecewaan?" },
  { text: "Apa satu hal tentang dirimu yang tidak akan pernah kamu ubah, meski ada kesempatan?" },
  { text: "Apakah kamu lebih suka realita atau fantasi (dalam film, buku, game)?" },
  { text: "Apa hal yang membuatmu merasa paling \"hidup\" dan bersemangat?" },
  { text: "Jika rumahmu terbakar dan kamu bisa menyelamatkan 3 benda (selain orang/hewan), apa itu?" },
  { text: "Apakah kamu merasa lebih mudah untuk memaafkan orang lain atau dirimu sendiri?" },
  { text: "Apa idiom atau pepatah favoritmu?" },
  { text: "Bagaimana kamu ingin dikenang oleh orang-orang?" },
  { text: "Apa satu hal yang akan kamu lakukan sekarang jika tahu besok adalah hari terakhirmu?" },
  { text: "Apakah kamu sering merasa bahwa orang lain tidak memahamimu?" },
  { text: "Apa yang lebih kamu takutkan: mencoba dan gagal, atau tidak mencoba sama sekali?" },
  { text: "Bagaimana caramu menunjukkan bahwa kamu peduli?" },
  { text: "Apa satu hal yang bisa membuatmu langsung kehilangan rasa hormat pada seseorang?" },
  { text: "Apakah kamu orang yang praktis atau idealis?" },
  { text: "Apa yang membuatmu merasa unik atau berbeda dari orang lain?" },
  { text: "Jika hatimu bisa berbicara sekarang, apa yang akan ia katakan?" },
  { text: "Apakah kamu lebih suka musim panas atau musim hujan? Mengapa?" },
  { text: "Apa yang biasanya kamu lakukan untuk \"mengisi ulang energi\" setelah lelah bersosialisasi?" },
  { text: "Jika ada satu hari dalam hidupmu yang bisa kamu jalani lagi, hari apa itu?" },
  { text: "Apakah kamu merasa terkoneksi dengan alam?" },
  { text: "Setelah menjawab semua pertanyaan ini, apa satu hal baru yang kamu sadari tentang dirimu?" },
  // --- Tema 2: Hubungan (100 Pertanyaan tentang Dinamika dengan Orang Lain) ---
  { text: "Apa kualitas nomor satu yang kamu cari dalam seorang pasangan?" },
  { text: "Bagaimana cara terbaik untuk menenangkanmu saat kamu sedang marah?" },
  { text: "Apakah kamu percaya pada konsep \"cinta sejati\"?" },
  { text: "Apa satu pertanyaan yang ingin selalu kamu tanyakan pada pasanganmu?" },
  { text: "Seberapa penting bagimu untuk memiliki hobi yang sama dengan pasangan?" },
  { text: "Apa yang membuatmu merasa dicintai dan dihargai?" },
  { text: "Bagaimana pendapatmu tentang hubungan jarak jauh?" },
  { text: "Apa satu sifat yang bisa langsung membuatmu \"ilfeel\" (hilang rasa) pada seseorang?" },
  { text: "Apakah kamu lebih suka pasangan yang perhatian atau yang memberi kebebasan?" },
  { text: "Bagaimana cara terbaik untuk memulai percakapan serius dengan pasangan?" },
  { text: "Pernahkah kamu mencintai seseorang tanpa kamu nyatakan? Ceritakan." },
  { text: "Apa arti \"komitmen\" bagimu dalam sebuah hubungan?" },
  { text: "Bagaimana pandanganmu tentang peran mantan dalam kehidupan pasanganmu sekarang?" },
  { text: "Apakah konflik itu pertanda hubungan tidak sehat, atau hal yang wajar?" },
  { text: "Seberapa penting bagi kamu untuk menyukai teman-teman pasanganmu?" },
  { text: "Menurutmu, apakah pasangan harus selalu jujur 100%?" },
  { text: "Apa gestur kecil yang paling berarti bagimu dari pasangan?" },
  { text: "Bagaimana reaksimu jika pasanganmu lupa ulang tahunmu?" },
  { text: "Apakah kamu tipe orang yang cemburuan? Apa yang membuatmu cemburu?" },
  { text: "Lebih suka menghabiskan waktu berkualitas di rumah atau pergi keluar bersama pasangan?" },
  { text: "Apa topik yang paling sulit untuk kamu diskusikan dengan pasangan?" },
  { text: "Menurutmu, apa yang membedakan hubungan yang bertahan lama dengan yang hanya sementara?" },
  { text: "Apakah kamu mudah jatuh cinta?" },
  { text: "Bagaimana cara kamu menunjukkan bahwa kamu tertarik pada seseorang?" },
  { text: "Jika pasanganmu memiliki mimpi yang mengharuskan dia pindah ke luar negeri, apa yang akan kamu lakukan?" },
  { text: "Apa yang lebih penting dalam sebuah hubungan: chemistry atau kecocokan?" },
  { text: "Seberapa penting faktor fisik dan penampilan dalam memilih pasangan?" },
  { text: "Bagaimana cara kamu meminta maaf setelah melakukan kesalahan?" },
  { text: "Apakah kamu percaya bahwa seseorang bisa mencintai dua orang sekaligus?" },
  { text: "Apa pengalaman kencan terbaik dan terburuk yang pernah kamu alami?" },
  { text: "Jika kamu bisa memberi satu nasihat untuk semua pasangan di dunia, apa itu?" },
  { text: "Apakah kamu tipe yang suka menjadi pusat perhatian pasangan?" },
  { text: "Bagaimana caramu membangun kepercayaan dengan seseorang yang baru kamu kenal?" },
  { text: "Apa satu hal yang tidak akan pernah kamu maafkan dalam suatu hubungan?" },
  { text: "Apakah menurutmu hubungan harus selalu bahagia atau boleh ada kesedihan?" },
  { text: "Bagaimana kamu ingin diperlakukan saat kamu sedang sedih?" },
  { text: "Apa pandanganmu tentang pernikahan?" },
  { text: "Seberapa sering kamu merasa perlu untuk \"me time\" dari pasangan?" },
  { text: "Apakah kamu percaya pada ide \"pasangan yang sempurna\"?" },
  { text: "Bagaimana cara terbaik untuk mengakhiri sebuah hubungan yang sudah tidak sehat?" },
  { text: "Apakah kamu lebih suka diajak ngobrol lewat chat, telepon, atau bertemu langsung?" },
  { text: "Apa satu hal kecil yang bisa dilakukan pasangan untuk membuat harimu lebih baik?" },
  { text: "Apakah kamu orang yang mudah melupakan kesalahan pasangan?" },
  { text: "Jika kamu dan pasangan punya selera humor yang sangat berbeda, apa yang akan terjadi?" },
  { text: "Apa batasan (boundaries) terpenting yang harus ada dalam sebuah hubungan?" },
  { text: "Menurutmu, apakah kita boleh menyimpan rahasia kecil dari pasangan?" },
  { text: "Bagaimana cara kamu menghadapi perbedaan pendapat yang prinsipil dengan pasangan?" },
  { text: "Apakah kamu merasa perlu untuk selalu update tentang kegiatan pasangan?" },
  { text: "Jika pasanganmu punya kebiasaan buruk yang mengganggu, apa yang akan kamu lakukan?" },
  { text: "Apa definisi \"kencan yang sempurna\" menurutmu?" },
  { text: "Apakah kamu lebih suka hubungan yang berkembang secara alami atau yang didefinisikan dengan jelas (misal, \"kita pacaran\")?" },
  { text: "Bagaimana reaksimu jika pasanganmu lebih sukses secara karier darimu?" },
  { text: "Apa arti \"rumah\" dalam sebuah hubungan?" },
  { text: "Apakah kamu tipe yang suka merencanakan masa depan bersama pasangan?" },
  { text: "Bagaimana caramu merayakan hari jadi atau momen spesial lainnya?" },
  { text: "Menurutmu, seberapa penting dukungan orangtua dan teman terhadap hubunganmu?" },
  { text: "Apakah kamu akan memaafkan perselingkuhan? Mengapa atau mengapa tidak?" },
  { text: "Apa satu hal yang ingin kamu pelajari dari hubungan orang tuamu?" },
  { text: "Bagaimana cara kamu membangun chemistry dengan seseorang?" },
  { text: "Apakah kamu percaya bahwa cinta bisa tumbuh seiring waktu?" },
  { text: "Siapa yang biasanya lebih dulu meminta maaf setelah bertengkar, kamu atau pasangan?" },
  { text: "Jika pasanganmu diam-diam membuat akun media sosial palsu untuk memantaumu, bagaimana perasaanmu?" },
  { text: "Apakah menurutmu pasangan harus memiliki visi dan misi hidup yang sama?" },
  { text: "Bagaimana caramu mengungkapkan bahwa kamu sedang tidak suka dengan sikap pasanganmu?" },
  { text: "Apakah kamu merasa bahwa cinta saja cukup untuk mempertahankan hubungan?" },
  { text: "Apa yang lebih sering kamu lakukan: mengingat masa lalu dengan mantan atau merencanakan masa depan dengan pasangan?" },
  { text: "Seberapa penting bagimu untuk memiliki pesta pernikahan yang mewah?" },
  { text: "Apakah kamu tipe yang suka bergaul dengan teman-teman pasangan?" },
  { text: "Bagaimana jika pasanganmu memiliki pandangan politik atau agama yang berbeda?" },
  { text: "Apa yang membuatmu yakin bahwa seseorang adalah \"orang yang tepat\"?" },
  { text: "Apakah kamu merasa mudah untuk mengatakan \"aku cinta kamu\"?" },
  { text: "Bagaimana pendapatmu tentang hubungan tanpa status (situationship)?" },
  { text: "Apa satu hal yang akan kamu lakukan untuk membuat pasanganmu merasa spesial hari ini?" },
  { text: "Apakah kamu percaya dengan konsep \"jodoh\" atau takdir dalam pertemuan?" },
  { text: "Bagaimana caramu menunjukkan apresiasi atas hal-hal kecil yang dilakukan pasangan?" },
  { text: "Menurutmu, apa penyebab utama kegagalan dalam sebuah hubungan?" },
  { text: "Apakah kamu termasuk orang yang posesif?" },
  { text: "Apa yang akan kamu lakukan jika pasanganmu ingin pindah agama demi menikahimu?" },
  { text: "Bagaimana cara kamu mengenali bahwa sebuah hubungan sudah waktunya berakhir?" },
  { text: "Seberapa penting bagimu pasanganmu dekat dengan keluargamu?" },
  { text: "Apakah kamu lebih suka kencan yang romantis, atau kencan yang seru dan penuh petualangan?" },
  { text: "Apa pertanyaan yang paling tidak ingin kamu dengar dari pasanganmu?" },
  { text: "Bagaimana perasaanmu jika pasanganmu masih berteman baik dengan mantannya?" },
  { text: "Apakah menurutmu, dalam hubungan yang sehat, boleh ada rasa iri?" },
  { text: "Bagaimana cara kamu mengembalikan mood positif setelah bertengkar hebat?" },
  { text: "Apakah kamu percaya bahwa cinta bisa berubah menjadi benci?" },
  { text: "Apa satu kebiasaan pasangan yang paling membuatmu bahagia?" },
  { text: "Jika pasanganmu sedang bermasalah, apakah kamu akan membantunya mencari solusi atau hanya menjadi pendengar?" },
  { text: "Menurutmu, apakah kita bisa benar-benar \"move on\" dari mantan?" },
  { text: "Seberapa penting komunikasi non-verbal (sentuhan, tatapan) bagimu?" },
  { text: "Apakah kamu tipe yang suka memberikan kejutan atau lebih suka diberi kejutan?" },
  { text: "Bagaimana cara kamu mengetahui bahwa kamu sedang jatuh cinta?" },
  { text: "Apa satu pelajaran terpenting yang kamu petik dari hubungan masa lalumu?" },
  { text: "Jika pasanganmu berkata, \"Aku butuh ruang,\" apa reaksimu?" },
  { text: "Apakah kamu percaya bahwa cinta pada pandangan pertama itu ada?" },
  { text: "Bagaimana pandanganmu tentang pernikahan beda agama atau beda suku?" },
  { text: "Seberapa penting kesetaraan peran dalam rumah tangga menurutmu?" },
  { text: "Apa yang lebih penting bagimu: kebahagiaan pasangan atau kebahagiaan diri sendiri?" },
  { text: "Jika bisa, satu hal apa yang ingin kamu ubah dari cara kamu menjalin hubungan selama ini?" },
  { text: "Apa definisi \"relationship goals\" versi pribadimu?" },
  // --- Tema 3: Masa Lalu (100 Pertanyaan tentang Kenangan) ---
  { text: "Apa kenangan masa kecil paling awal yang bisa kamu ingat?" },
  { text: "Siapa orang yang paling berpengaruh di masa kecilmu selain orangtua?" },
  { text: "Apa makanan favoritmu dulu yang sekarang sudah jarang kamu temui?" },
  { text: "Ceritakan tentang mainan kesayanganmu yang hilang atau rusak." },
  { text: "Apa lagu masa kecil yang masih melekat di ingatanmu sampai sekarang?" },
  { text: "Siapa guru SD yang paling kamu ingat? Kenangan apa yang membuatnya berkesan?" },
  { text: "Apa profesi cita-citamu waktu kecil, dan apa jadinya sekarang?" },
  { text: "Ceritakan satu kenangan memalukan di masa sekolah yang hingga kini masih kamu ingat." },
  { text: "Apa film atau acara TV favoritmu saat masih kecil?" },
  { text: "Siapa teman terbaikmu waktu kecil dan kenapa kalian bisa dekat?" },
  { text: "Apa hukuman paling berkesan yang pernah diberikan orangtuamu?" },
  { text: "Pernahkah kamu mengalami patah hati pertama? Seperti apa rasanya?" },
  { text: "Apa satu kebohongan terbesar yang pernah kamu katakan pada orangtuamu?" },
  { text: "Ceritakan satu momen liburan keluarga yang paling berkesan (baik atau buruk)." },
  { text: "Apa yang paling kamu takuti saat masih kecil? Apakah ketakutan itu masih ada?" },
  { text: "Siapa selebriti atau tokoh publik yang menjadi \"crush\" pertamamu?" },
  { text: "Apa kenangan tentang sahabat kecilmu yang paling kamu rindukan?" },
  { text: "Apakah ada benda pusaka atau warisan keluarga yang memiliki cerita khusus?" },
  { text: "Ceritakan tentang hewan peliharaan pertamamu." },
  { text: "Apa kenangan buruk tentang seseorang yang tidak bisa kamu lupakan hingga kini?" },
  { text: "Apakah ada momen di mana kamu merasa sangat tidak diinginkan atau sendirian?" },
  { text: "Siapa yang pertama kali membuatmu merasakan jatuh cinta?" },
  { text: "Apa hal bodoh yang pernah kamu lakukan demi mendapatkan perhatian seseorang?" },
  { text: "Ceritakan tentang buku pertama yang sangat kamu sukai." },
  { text: "Apa prestasi masa kecil yang paling kamu banggakan?" },
  { text: "Apakah ada luka fisik di tubuhmu yang punya cerita unik di baliknya?" },
  { text: "Apa yang paling kamu sesali saat masih remaja?" },
  { text: "Siapa orang dewasa di luar keluargamu yang sangat baik padamu waktu kecil?" },
  { text: "Ceritakan tentang pesta ulang tahunmu yang paling berkesan." },
  { text: "Apa tren atau gaya rambut paling aneh yang pernah kamu ikuti?" },
  { text: "Pernahkah kamu menyaksikan pertengkaran hebat orangtuamu? Bagaimana perasaanmu saat itu?" },
  { text: "Apa mimpi buruk yang paling sering kamu alami saat kecil?" },
  { text: "Siapa musuh bebuyutanmu di sekolah dan kenapa kalian bisa bermusuhan?" },
  { text: "Ceritakan satu momen di mana kamu merasa sangat malu pada orangtuamu di depan umum." },
  { text: "Apa lagu yang paling sering kamu nyanyikan saat masih kecil?" },
  { text: "Apa hadiah terbaik yang pernah kamu terima saat kecil?" },
  { text: "Apakah ada rahasia kecil yang kamu simpan dari orangtuamu dan baru terungkap bertahun-tahun kemudian?" },
  { text: "Bagaimana kenangan pertamamu tentang uang? Kapan pertama kali kamu punya uang sendiri?" },
  { text: "Siapa orang yang paling sering kamu andalkan saat kamu punya masalah waktu kecil?" },
  { text: "Apa yang paling kamu benci untuk dimakan saat kecil, dan bagaimana perasaanmu tentang makanan itu sekarang?" },
  { text: "Ceritakan tentang satu kecelakaan kecil (jatuh dari sepeda, dll.) yang pernah kamu alami." },
  { text: "Apa yang paling kamu rindukan dari masa kecilmu yang tidak bisa kamu dapatkan sekarang?" },
  { text: "Apakah ada satu nasihat dari orangtua atau guru yang masih kamu pegang sampai sekarang?" },
  { text: "Ceritakan tentang sahabat pena atau teman korespondensi yang pernah kamu miliki." },
  { text: "Apa permainan tradisional favoritmu saat kecil?" },
  { text: "Pernahkah kamu merasa iri pada teman yang memiliki sesuatu yang kamu tidak punya?" },
  { text: "Apa acara televisi yang selalu kamu tunggu-tunggu setiap hari?" },
  { text: "Siapa orang yang pertama kali mengajarkanmu tentang agama atau kepercayaan?" },
  { text: "Ceritakan tentang momen pertama kali kamu naik sepeda tanpa roda bantu." },
  { text: "Apa kue atau jajanan pasar favoritmu waktu kecil?" },
  { text: "Apakah ada mimpi atau cita-cita masa kecil yang sudah berhasil kamu wujudkan?" },
  { text: "Siapa yang paling membuatmu merasa aman saat kamu masih kecil?" },
  { text: "Pernahkah kamu mengalami peristiwa alam yang menakutkan (gempa, banjir, dll.)?" },
  { text: "Apa satu hal yang orangtuamu selalu katakan yang dulu kamu benci tapi sekarang kamu sadar itu benar?" },
  { text: "Ceritakan tentang kegiatan ekstrakurikuler pertama yang kamu ikuti." },
  { text: "Apakah ada satu foto lama yang memiliki cerita sangat berharga bagimu?" },
  { text: "Siapa orang yang menginspirasimu untuk menjadi seperti sekarang ini?" },
  { text: "Pernahkah kamu pindah rumah atau sekolah?" },
  { text: "Bagaimana perasaanmu saat itu?" },
  { text: "Apa yang pertama kali kamu rasakan saat bertemu adik atau kakak barumu?" },
  { text: "Ceritakan tentang momen kamu mendapat nilai jelek di sekolah dan reaksi orangtuamu." },
  { text: "Apakah ada benda atau tempat dari masa lalu yang ingin sekali kamu kunjungi lagi?" },
  { text: "Siapa tokoh fiksi (kartun, buku) yang paling kamu idolakan?" },
  { text: "Bagaimana perasaanmu saat pertama kali tahu bahwa Sinterklas atau Tooth Fairy itu tidak nyata?" },
  { text: "Apa kata-kata kasar pertama yang kamu ucapkan dan dari mana kamu mendengarnya?" },
  { text: "Ceritakan tentang sahabat yang pernah sangat dekat tapi sekarang sudah tidak berhubungan lagi." },
  { text: "Apa yang paling membuatmu takut saat akan tidur malam?" },
  { text: "Pernahkah kamu mengalami peristiwa yang membuatmu trauma hingga dewasa?" },
  { text: "Siapa orang pertama yang membuatmu sadar tentang perbedaan status sosial?" },
  { text: "Apakah ada lagu atau musik tertentu yang langsung membawamu kembali ke masa lalu?" },
  { text: "Ceritakan tentang koleksi barang yang pernah kamu buat (perangko, stiker, batu, dll.)." },
  { text: "Apa acara keluarga yang paling tidak pernah kamu lewatkan saat kecil?" },
  { text: "Apakah kamu punya kenangan tentang kakek atau nenek yang sangat berkesan?" },
  { text: "Siapa yang paling sering menjemputmu di sekolah?" },
  { text: "Ceritakan tentang momen kamu tersesat atau kehilangan orangtua di tempat ramai." },
  { text: "Apa hal yang paling membuatmu frustrasi saat belajar sesuatu di masa kecil?" },
  { text: "Pernahkah kamu berkelahi secara fisik dengan teman? Apa penyebabnya?" },
  { text: "Bagaimana perasaanmu saat pertama kali menaiki wahana permainan yang menegangkan?" },
  { text: "Apa hal teraneh yang pernah kamu percayai sebagai sebuah kebenaran?" },
  { text: "Siapa orang dewasa yang paling kamu kagumi di luar keluarga?" },
  { text: "Ceritakan tentang momen kamu diam-diam mengambil sesuatu yang bukan milikmu (uang orangtua, permen di toko)." },
  { text: "Apa warna favoritmu saat kecil dan apakah sekarang masih sama?" },
  { text: "Siapa yang pertama kali mengajarkanmu tentang kehilangan atau kematian?" },
  { text: "Apakah ada sebuah rahasia keluarga yang baru kamu ketahui setelah dewasa?" },
  { text: "Ceritakan tentang pertunjukan bakat atau pentas seni pertama yang kamu ikuti." },
  { text: "Apa yang paling kamu nanti-nantikan saat hari libur sekolah tiba?" },
  { text: "Pernahkah kamu menjadi korban bully atau sebaliknya? Ceritakan." },
  { text: "Siapa orang yang paling kamu percaya untuk berbagi rahasia saat remaja?" },
  { text: "Apa satu kenangan tentang rumah masa kecilmu yang paling ingin kamu abadikan?" },
  { text: "Ceritakan tentang mobil atau kendaraan pertama yang kamu ingat ditumpangi." },
  { text: "Apakah ada profesi yang dulu kamu anggap keren tapi sekarang kamu sadar realitanya berbeda?" },
  { text: "Siah tokoh sejarah pertama yang membuatmu terinspirasi?" },
  { text: "Apa hadiah yang paling tidak kamu sukai saat kecil?" },
  { text: "Pernahkah kamu mengalami kegagalan besar yang membuatmu malu saat itu?" },
  { text: "Bagaimana cara orangtuamu menanamkan nilai tentang uang dan menabung?" },
  { text: "Ceritakan tentang satu momen di mana kamu merasa sangat tidak adil diperlakukan." },
  { text: "Apa olahraga atau aktivitas fisik yang paling kamu sukai di masa kecil?" },
  { text: "Siapa artis pertama yang fotonya pernah kamu tempel di dinding kamar?" },
  { text: "Apakah ada makanan atau bau tertentu yang selalu mengingatkanmu pada orang tertentu?" },
  { text: "Apa satu pelajaran hidup terpenting yang kamu petik dari masa lalumu?" },
  { text: "Jika kamu bisa kembali ke masa lalu dan memberi pesan pada dirimu yang berusia 15 tahun, apa yang akan kamu katakan?" },
  // --- Tema 4: Kehidupan (100 Pertanyaan Refleksi dan Pandangan ke Depan) ---
  { text: "Apa rutinitas pagi yang ideal menurutmu?" },
  { text: "Jika kamu punya satu keinginan yang bisa dikabulkan sekarang, apa yang akan kamu minta?" },
  { text: "Apa satu hal dalam hidupmu yang kamu rasa sudah sangat tepat dan tidak ingin kamu ubah?" },
  { text: "Apa yang biasanya membuatmu stres, dan bagaimana cara terbaikmu mengatasinya?" },
  { text: "Menurutmu, apakah hidup ini sudah adil?" },
  { text: "Apa target terbesar yang ingin kamu capai dalam 5 tahun ke depan?" },
  { text: "Jika kamu bisa hidup di era mana pun (masa lalu, sekarang, masa depan), era mana yang akan kamu pilih?" },
  { text: "Apa definisi \"kehidupan yang baik\" versimu?" },
  { text: "Siapa orang yang paling berjasa dalam membentuk jalan hidupmu?" },
  { text: "Apakah kamu tipe orang yang puas dengan apa yang ada, atau selalu ingin lebih?" },
  { text: "Apa satu kebiasaan baik yang ingin kamu terapkan mulai sekarang?" },
  { text: "Jika kamu punya kekuatan untuk mengubah satu hal dalam sistem pendidikan atau pekerjaan, apa itu?" },
  { text: "Apa yang lebih kamu takutkan: masa depan yang tidak pasti, atau terjebak di masa lalu?" },
  { text: "Bagaimana cara kamu melihat kegagalan: sebagai akhir atau sebagai pelajaran?" },
  { text: "Apa hal paling berani yang ingin kamu lakukan tapi belum terlaksana?" },
  { text: "Apakah lingkungan tempat tinggalmu sekarang sudah sesuai dengan yang kamu impikan?" },
  { text: "Jika hidup ini adalah sebuah petualangan, apa \"side quest\" (misi sampingan) yang sedang kamu jalani?" },
  { text: "Apa peran teknologi dalam hidupmu? Apakah terlalu dominan?" },
  { text: "Menurutmu, apa yang paling dibutuhkan oleh generasi muda saat ini?" },
  { text: "Seberapa penting bagimu untuk meninggalkan warisan atau dampak bagi dunia?" },
  { text: "Apa satu hal kecil yang bisa dilakukan banyak orang untuk membuat dunia lebih baik?" },
  { text: "Apakah kamu lebih suka hidup di kota besar yang ramai atau di desa yang tenang?" },
  { text: "Apa satu hal yang ingin kamu pelajari atau kuasai di tahun ini?" },
  { text: "Bagaimana kamu menjaga kesehatan mental di tengah hiruk-pikuk kehidupan?" },
  { text: "Apakah kamu merasa bahwa kehidupan sosialmu saat ini sudah cukup memuaskan?" },
  { text: "Apa arti \"kebebasan\" bagimu?" },
  { text: "Jika kamu punya banyak uang, masalah sosial apa yang pertama kali ingin kamu bantu selesaikan?" },
  { text: "Apa satu momen dalam hidupmu yang membuatmu percaya pada keajaiban?" },
  { text: "Bagaimana perasaanmu tentang proses menua?" },
  { text: "Apa satu kualitas terpenting yang harus dimiliki seorang pemimpin di dunia saat ini?" },
  { text: "Apakah kamu termasuk orang yang optimis atau pesimis tentang masa depan umat manusia?" },
  { text: "Apa hal yang paling sering mengganggu pikiranmu di malam hari?" },
  { text: "Jika hidupmu adalah sebuah teka-teki, potongan apa yang paling sulit kamu temukan?" },
  { text: "Apa yang membuatmu merasa paling bersyukur menjadi dirimu sendiri?" },
  { text: "Menurutmu, apa kunci untuk mencapai kebahagiaan sejati?" },
  { text: "Jika kamu bisa memulai sebuah organisasi atau gerakan sosial, isu apa yang akan kamu angkat?" },
  { text: "Bagaimana cara kamu berkontribusi untuk lingkungan atau masyarakat sekitar?" },
  { text: "Apakah ada buku atau film yang mengubah cara pandangmu tentang hidup?" },
  { text: "Apa satu hal yang akan kamu lakukan secara berbeda jika kamu bisa memutar waktu?" },
  { text: "Apakah menurutmu hidup ini tentang mengejar kebahagiaan atau tentang menemukan makna?" },
  { text: "Apa yang lebih penting: mempunyai banyak teman atau beberapa teman yang sangat dekat?" },
  { text: "Bagaimana cara kamu menghadapi orang-orang yang toksik di sekitarmu?" },
  { text: "Apa satu pencapaian non-materi yang paling kamu banggakan?" },
  { text: "Jika kamu tahu ini adalah tahun terakhirmu di bumi, bagaimana kamu akan menghabiskannya?" },
  { text: "Apakah kamu merasa sudah menemukan \"panggilan jiwa\" atau passion dalam hidupmu?" },
  { text: "Apa pendapatmu tentang konsep \"work-life balance\"?" },
  { text: "Seberapa sering kamu meluangkan waktu untuk merenung dan berefleksi?" },
  { text: "Apa satu hal yang ingin kamu pesan kepada generasi setelahmu?" },
  { text: "Jika bisa, satu kebiasaan buruk apa yang ingin kamu 'hapus' dari masyarakat modern?" },
  { text: "Apakah kamu percaya pada karma atau hukum sebab akibat?" },
  { text: "Bagaimana cara kamu mendefinisikan \"kesuksesan\" di usiamu sekarang?" },
  { text: "Apa yang membuatmu merasa paling optimis tentang masa depan?" },
  { text: "Menurutmu, apa peran utama keluarga dalam kehidupan seseorang?" },
  { text: "Apakah kamu merasa bahwa hidupmu saat ini terlalu sibuk atau terlalu membosankan?" },
  { text: "Apa satu pelajaran berharga yang kamu dapatkan dari orang yang tidak kamu sukai?" },
  { text: "Jika hidup adalah sekolah, pelajaran apa yang paling ingin kamu lewati?" },
  { text: "Bagaimana caramu melepaskan diri dari tekanan dan ekspektasi sosial?" },
  { text: "Apakah kamu lebih suka stabilitas atau petualangan dalam hidup?" },
  { text: "Apa yang akan kamu lakukan jika kamu tahu besok adalah hari kiamat?" },
  { text: "Apa satu hal yang menurutmu sangat \"overrated\" dalam kehidupan modern?" },
  { text: "Siapa orang yang paling membuatmu terinspirasi untuk menjadi pribadi yang lebih baik?" },
  { text: "Apakah kamu percaya bahwa segala sesuatu terjadi karena suatu alasan?" },
  { text: "Bagaimana pandanganmu tentang kematian?" },
  { text: "Apa momen paling \"surreel\" atau tidak nyata yang pernah kamu alami?" },
  { text: "Jika kamu bisa mengajukan satu pertanyaan dan mendapatkan jawaban jujur dari seluruh umat manusia, apa pertanyaanmu?" },
  { text: "Menurutmu, apa kekuatan terbesar dan kelemahan terbesar generasimu?" },
  { text: "Apakah kamu merasa sudah cukup berempati pada kondisi orang lain?" },
  { text: "Apa satu hal yang akan kamu pertahankan mati-matian sebagai prinsip hidup?" },
  { text: "Bagaimana cara kamu menyikapi berita-berita buruk atau negatif yang terjadi di dunia?" },
  { text: "Jika kamu punya kesempatan untuk menjadi sangat terkenal, apakah kamu akan mengambilnya?" },
  { text: "Apa yang paling kamu cari dalam sebuah komunitas atau lingkungan pertemanan?" },
  { text: "Apakah kamu merasa bahwa hidupmu memiliki ritme atau pola tertentu?" },
  { text: "Apa satu hal yang ingin kamu wujudkan untuk orang-orang yang kamu cintai?" },
  { text: "Bagaimana kamu ingin diingat oleh orang-orang setelah kamu tiada?" },
  { text: "Apakah ada hal dalam hidupmu yang rela kamu korbankan demi sesuatu yang lebih besar?" },
  { text: "Menurutmu, apakah manusia pada dasarnya baik atau jahat?" },
  { text: "Apa satu hal yang membuatmu kehilangan kepercayaan pada sistem atau institusi?" },
  { text: "Bagaimana kamu melihat peran seni dan budaya dalam kehidupan?" },
  { text: "Apakah kamu lebih suka menjadi orang biasa dengan hidup luar biasa, atau orang luar biasa dengan hidup biasa?" },
  { text: "Apa yang akan kamu lakukan jika tiba-tiba kamu mendapatkan kekayaan yang sangat besar?" },
  { text: "Bagaimana caramu bersikap terhadap seseorang yang memiliki pandangan hidup sangat berbeda denganmu?" },
  { text: "Menurutmu, apa satu masalah global yang paling mendesak untuk segera diatasi?" },
  { text: "Apakah kamu merasa sudah cukup banyak membantu sesama?" },
  { text: "Apa definisi \"cinta\" dalam konteks kehidupan yang lebih luas (bukan hanya romantis)?" },
  { text: "Jika hidup ini adalah sebuah cerita, apa genre-nya?" },
  { text: "Apa satu hal yang ingin kamu sampaikan kepada seluruh umat manusia?" },
  { text: "Apakah kamu percaya pada kehidupan setelah mati?" },
  { text: "Bagaimana cara kamu menemukan harapan di saat-saat tergelap?" },
  { text: "Apakah kamu lebih sering menyesali masa lalu atau mencemaskan masa depan?" },
  { text: "Apa satu kualitas yang ingin kamu wariskan kepada anak cucumu kelak?" },
  { text: "Menurutmu, apa yang paling membedakan manusia dengan makhluk lain?" },
  { text: "Apa peran penting seorang teman dalam menjalani kehidupan?" },
  { text: "Bagaimana perasaanmu saat melihat ketidakadilan terjadi di sekitarmu?" },
  { text: "Apakah kamu merasa bahwa usahamu selama ini sebanding dengan hasil yang kamu dapat?" },
  { text: "Apa satu hal yang membuatmu tetap bertahan dan bersemangat menjalani hari?" },
  { text: "Jika hidup ini adalah sebuah marathon, di titik mana kamu merasa berada sekarang?" },
  { text: "Apakah ada satu filosofi atau ajaran tertentu yang sangat mempengaruhi hidupmu?" },
  { text: "Bagaimana cara kamu merayakan keberadaanmu di dunia ini?" },
  { text: "Apa satu pertanyaan tentang kehidupan yang belum terjawab hingga kini?" },
  { text: "Setelah merenungkan semua pertanyaan tentang kehidupan ini, apa satu resolusi atau tekad yang muncul dalam dirimu?" }
];